//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.09 at 11:30:54 AM IDT 
//


package superDuperMarketRegion;

import DtoObjects.PurchaseCategory;
import generatedClassesJaxb.SDMItem;


public class Item {

    private String name;
    private PurchaseCategory purchaseCategory;
    private int id;
    private int sellersNum;
    public Item(SDMItem sdmItem)
    {
        setId(sdmItem.getId());
        setName(sdmItem.getName());
        this.purchaseCategory=  PurchaseCategory.valueOf(sdmItem.getPurchaseCategory());
        sellersNum=0;
    }
    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    public PurchaseCategory getPurchaseCategory() {
        return purchaseCategory;
    }

    public void setPurchaseCategory(PurchaseCategory purchaseCategory) {
        this.purchaseCategory = purchaseCategory;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    public int getSellersNum() {
        return sellersNum;
    }

    public void setSellersNum(int sellersNum) {
        this.sellersNum = sellersNum;
    }

    public void increaseSellersNumByOne()
    {
        this.sellersNum++;
    }

    public void decreaseSellersNumByOne()
    {
        this.sellersNum--;
    }

}
